# UwU desktop configuration entry point.
# Feature files are automatically imported top-level modules; this entry point
# only selects the merged roles that form the machine.
{ config, inputs, ... }:
{
  flake.nixosConfigurations.UwU = inputs.nixpkgs.lib.nixosSystem {
    system = "x86_64-linux";

    modules = [
      inputs.disko.nixosModules.disko
      config.nixos.modules.common
      config.nixos.modules.privateAccounts
      config.nixos.modules.remoteMesh
      config.nixos.modules.fileManager
      config.nixos.modules.personal
      config.nixos.modules.virtualisation
      config.nixos.modules.adLab
      config.nixos.modules.disk
      config.nixos.hosts.UwU

      # Generated by nixos-generate-config; deliberately remains a lower-level
      # module so regeneration tools can replace it safely.
      ./hardware-configuration.nix

      # witr — process/port/container/file tracing CLI. See flake.nix.
      inputs.self.nixosModules.witr

      { nixpkgs.overlays = [ inputs.self.overlays.additions ]; }
      { nixpkgs.overlays = [ inputs.self.overlays.python-package-fixes ]; }
      { nixpkgs.overlays = [ (import ../../overlays/millennium.nix { millennium-input = inputs.millennium; }) ]; }
      { nixpkgs.overlays = [ (import ../../overlays/amneziawg-kernel7-fix.nix) ]; }
      {
        services.privateMesh = {
          nodeRole = "private";
          exposeSshOnLan = false;
        };
      }
    ];
  };
}
