# UwU desktop configuration entry point.
# Feature files are automatically imported top-level modules; this entry point
# only selects the merged roles that form the machine.
{ config, inputs, ... }:
{
  flake.nixosConfigurations.UwU = inputs.nixpkgs.lib.nixosSystem {
    system = "x86_64-linux";

    modules = [
      inputs.disko.nixosModules.disko
      config.nixos.modules.common
      config.nixos.modules.privateAccounts
      config.nixos.modules.netbirdMesh
      config.nixos.modules.fileManager
      config.nixos.modules.office
      config.nixos.modules.personal
      config.nixos.modules.virtualisation
      config.nixos.modules.adLab
      config.nixos.modules.disk
      config.nixos.modules.maintenance
      config.nixos.modules.observability
      config.nixos.hosts.UwU

      # Generated by nixos-generate-config; deliberately remains a lower-level
      # module so regeneration tools can replace it safely.
      ./hardware-configuration.nix

      # Prometheus node_exporter — direct import (the walker excludes it
      # from flake-parts imports because networking.firewall.* trips
      # flake-parts evaluation; see flake.nix's dendriticExceptions).
      # Opt-in by adding this direct import.
      ./../modules/observability/node-exporter.nix

      # Heartbeat dead-man's-switch — same pattern as node-exporter.nix.
      # See flake.nix's dendriticExceptions for the rationale.
      ./../modules/maintenance/heartbeat.nix

      # btrfs monthly scrub — same pattern as node-exporter.nix.
      # See flake.nix's dendriticExceptions for the rationale.
      ./../modules/disko/btrfs-scrub.nix

      # witr — process/port/container/file tracing CLI. See flake.nix.
      inputs.self.nixosModules.witr

      { nixpkgs.overlays = [ inputs.self.overlays.additions ]; }
      { nixpkgs.overlays = [ inputs.self.overlays.python-package-fixes ]; }
      { nixpkgs.overlays = [ (import ../../overlays/millennium.nix { millennium-input = inputs.millennium; }) ]; }
      { nixpkgs.overlays = [ (import ../../overlays/amneziawg-kernel7-fix.nix) ]; }
      {
        # Netbird mesh — sole mesh on this host as of 2026-08-09.
        # See docs/netbird-mesh.md for the migration rationale. The
        # pre-Netbird mesh (Tailscale) had its remoteMesh opt-in
        # removed in the same commit.
        services.netbirdMesh = {
          enable = true;
          nodeRole = "private";
          exposeSshOnLan = false;
          # DMS NetbirdStatus plugin + netbird-ui GUI both hardcode
          # `which netbird`; the role module builds a passthrough shim
          # that wraps `netbird-mesh` under the bare name.
          dms.enable = true;
        };
      }
    ];
  };
}
