# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # NOTE: fileSystems are now managed declaratively by disko (disk-layout.nix).
  # These entries are kept as fallbacks with mkDefault so disko's values win.
  # When reinstalling via nixos-anywhere, this file will be regenerated and
  # these entries can be removed entirely (disko handles everything).
  fileSystems."/" = lib.mkDefault
    { device = "/dev/disk/by-uuid/129f8c1b-2bec-4502-9fef-d96e8103be8b";
      fsType = "xfs";
    };

  fileSystems."/boot" = lib.mkDefault
    { device = "/dev/disk/by-uuid/A767-B462";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
