# YubiKey FIDO2 authentication for PAM services
#
# Enables YubiKey as an ALTERNATIVE to password for:
#   - greetd (graphical login / DankGreeter)
#   - login  (TTY login)
#   - sudo   (privilege escalation)
#
# With control = "sufficient", PAM accepts the YubiKey touch OR the
# regular password — whichever is provided first succeeds.
#
# SETUP (after deploying this config):
#   1. Insert a YubiKey
#   2. Run:  pamu2fcfg -u jaide
#      (touch the YubiKey when it flashes)
#   3. Repeat for each backup key:  pamu2fcfg -u jaide -n
#   4. Append all output lines to ~/.config/Yubico/u2f_keys
#   5. Test in a NEW terminal:  sudo -k && sudo true
#
# For LUKS boot unlock, see hardware/luks.nix — that uses
# systemd-cryptenroll (separate from PAM, enrolled per-device).
{ ... }: {
  # Enable the pam_u2f module globally
  security.pam.u2f = {
    enable = true;
    # "sufficient" = key OR password (alternative, not 2FA)
    control = "sufficient";
    # Per-user key files: ~/.config/Yubico/u2f_keys
    # (generated by `pamu2fcfg -u jaide`)
    settings = {
      # Prompt "Insert your security key and touch it" rather than
      # silently waiting for a touch
      cue = true;
      # Use the appid string so the key is bound to this hostname
      appid = "pam://TSBW-W01800";
    };
  };

  # Enable u2fAuth on the services we want key-based unlock for.
  # These default to security.pam.u2f.enable (true), but being
  # explicit avoids surprises if the global default changes.
  security.pam.services = {
    greetd.u2f.enable = true;   # DankGreeter (graphical login)
    login.u2f.enable = true;    # TTY login
    sudo.u2f.enable = true;     # sudo
  };
}