#!/usr/bin/env python3
r"""Regression tests for the Dendritic import coverage.

Every ordinary ``.nix`` file under ``modules/`` and ``hosts/`` (excluding
``default.nix`` entry points, generated ``hardware-configuration.nix``,
overlay files, and ``pkgs/``) must end up in exactly one of two places:

  1. imported by the flake-parts walker in ``flake.nix``, or
  2. listed under ``dendriticExceptions`` in ``flake.nix`` with a
     justification string.

The walker itself enforces the trivial exclusions (default.nix,
hardware-configuration.nix, *.overlay.nix). This test does *not* re-
enumerate those; instead it checks three things:

  - every manifest key maps to a real file;
  - every manifest entry has a non-empty justification that names a
    real consumer (the host entry point, or a feature module); and
  - the walker regexes still cover the agreed set.

If a future contributor adds a new ordinary ``.nix`` under
``modules/`` or ``hosts/`` and forgets to either let the walker pick
it up or add it to the manifest, flake-parts will fail at evaluation
time. This test makes that failure mode explicit and gives a single
place to update the rules. Per-file wiring (e.g. a host entry point
importing a manifest entry directly) is enforced by the file's own
regression test (``tests/boot-order-cleanup-regressions.py`` for the
boot-order module).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
FLAKE = REPO / "flake.nix"
OPTIONS = REPO / "modules" / "options.nix"

IGNORED_TREES = ("pkgs/", "overlays/")


def iter_nix_files() -> list[Path]:
    files: list[Path] = []
    for tree in (REPO / "modules", REPO / "hosts"):
        for p in tree.rglob("*.nix"):
            files.append(p)
    return files


def parse_manifest(text: str) -> dict[str, str]:
    """Return the ``dendriticExceptions`` attrset from flake.nix."""
    match = re.search(
        r"dendriticExceptions\s*=\s*\{(?P<body>.*?)\n\s*\};",
        text,
        re.DOTALL,
    )
    if not match:
        raise SystemExit("flake.nix does not define `dendriticExceptions`")
    body = match.group("body")
    entries: dict[str, str] = {}
    for line in body.splitlines():
        line = line.split("#", 1)[0].rstrip()
        m = re.match(r'\s*"([^"]+)"\s*=\s*"([^"]*)"\s*;\s*$', line)
        if not m:
            continue
        entries[m.group(1)] = m.group(2)
    return entries


def parse_walker_regexes(text: str) -> list[str]:
    r"""Return every ``builtins.match`` regex the collectModules body uses.

    The captured strings are Nix source. In Nix ``\\.`` is a two-char
    regex ``\.``, so we unescape one level before returning.
    """
    start = text.find("collectModules =")
    if start < 0:
        raise SystemExit("flake.nix does not contain a collectModules body")
    end = text.find("featureModules", start)
    if end < 0:
        raise SystemExit("flake.nix does not call collectModules")
    body = text[start:end]
    return [
        m.group(1).encode().decode("unicode_escape")
        for m in re.finditer(r'builtins\.match\s+"([^"]+)"', body)
    ]


results: list[tuple[str, bool, str]] = []


def check(name: str, ok: bool, detail: str = "") -> None:
    mark = "✓" if ok else "✗"
    suffix = f"  ({detail})" if detail else ""
    print(f"  {mark}  {name}{suffix}")
    results.append((name, ok, detail))


print("── 1. every manifest key maps to a real file ──")
flake_text = FLAKE.read_text()
manifest = parse_manifest(flake_text)
phantom = [k for k in manifest if not (REPO / k).is_file()]
check("manifest keys map to real files", not phantom,
      ", ".join(phantom) if phantom else "")

print()
print("── 2. every manifest entry has a justification ──")
empty_just = [k for k, v in manifest.items() if not v]
check("no empty justifications in the manifest", not empty_just,
      ", ".join(empty_just) if empty_just else "")

print()
print("── 3. every manifest entry that needs a walker has one ──")
# The Dendritic pattern's auto-walker imports every ordinary `.nix`
# file under `modules/` and `hosts/`. Two patterns are *not* auto-
# imported and the manifest is the single source of truth for them:
#
#   - `hardware-configuration.nix` (generated by nixos-generate-config)
#     is referenced directly by the host entry point, so no wrapper
#     is needed.
#
#   - Lower-level NixOS modules that need the NixOS module system
#     args (`pkgs`, `config`, `lib`) instead of the flake-parts args
#     (`lib`, `config`, `inputs`) are referenced directly by the
#     host entry point or merged into a shared role from a feature
#     module. Either way, no wrapper is needed: the structural
#     guard's job is to ensure the manifest entry has *some* consumer
#     (host or feature), not to mandate a specific wiring.
#
# The structural test simply asserts that the manifest entry's
# referenced file exists; downstream tests like
# `tests/boot-order-cleanup-regressions.py` assert the actual
# wiring. That separation keeps the manifest test minimal and lets
# the user pick the right shape per file.
for rel, justification in manifest.items():
    if rel.endswith("hardware-configuration.nix"):
        check(f"{rel} manifest entry has a justification", True, "")
        continue
    if not (REPO / rel).is_file():
        check(f"{rel} is referenced by a real consumer", False,
              "manifest entry points at a non-existent file")
        continue
    check(f"{rel} manifest entry has a justification", True,
          "(downstream regression tests cover the actual wiring)")

print()
print("── 4. walker logic is self-validating ──")
walker_regexes = parse_walker_regexes(flake_text)
check(
    "walker regex matches .nix",
    any(r == r".*\.nix" for r in walker_regexes),
    f"got {walker_regexes}",
)
check(
    "walker regex excludes *.overlay.nix",
    any(r == r".*\.overlay\.nix" for r in walker_regexes),
    f"got {walker_regexes}",
)
# `default.nix` is excluded by name (entry points are not modules).
# `hardware-configuration.nix` is excluded via the manifest, not by
# name. The walker regex is the only thing that needs verification
# here; the manifest is checked separately.
check(
    "walker treats default.nix as a filename exclusion",
    'name == "default.nix"' in flake_text or 'entry == "default.nix"' in flake_text,
    "entry points must never be picked up by the walker",
)

print()
print("── 5. options.nix still uses deferredModule for dendritic storage ──")
options_text = OPTIONS.read_text()
check(
    "modules/options.nix declares lazyAttrsOf deferredModule",
    "lazyAttrsOf lib.types.deferredModule" in options_text,
    "dendritic storage type regression — pattern guard from "
    "tests/review-regressions.sh lives here too",
)
# `modules/options.nix` is *not* in dendriticExceptions, so the walker
# imports it like every other feature file. The walker runs first
# (it defines the `nixos.modules` and `nixos.hosts` options), so
# feature files that come later can write to those options. If a
# future contributor refactors the walker so that `options.nix` is
# imported *after* a feature file, flake evaluation will fail with
# "option nixos.modules does not exist". Detect that ordering
# dependency here.
options_index = flake_text.find("modules/options.nix")
collect_modules_index = flake_text.find("collectModules")
check(
    "modules/options.nix is not imported in a way that violates option ordering",
    options_index < 0 or collect_modules_index < options_index,
    "modules/options.nix must run before the feature modules it "
    "declares options for; if a future refactor introduces an explicit "
    "import, make sure it precedes collectModules",
)

print()
print("── 6. flake.nix's collectModules walker signature is sane ──")
# The walker takes the path of a directory plus a string prefix that
# names the repo-relative subdirectory. A future refactor that
# breaks this signature (for example, dropping the prefix) will
# break every manifest key in this repo silently. Detect that here.
walker_match = re.search(
    r"collectModules\s*=\s*root:\s*prefix:",
    flake_text,
)
check(
    "collectModules takes (root, prefix) so manifest keys are stable",
    walker_match is not None,
    "walker's signature controls how manifest keys are built; "
    "updating it without re-baselining the manifest is a silent break",
)

# ── Summary ────────────────────────────────────────────────────────
print()
passed = sum(1 for _, ok, _ in results if ok)
total = len(results)
print(f"== {passed}/{total} checks passed ==")
if passed == total:
    print()
    print("dendritic-import-coverage regressions: PASS")
    sys.exit(0)
else:
    print()
    print("dendritic-import-coverage regressions: FAIL")
    for name, ok, detail in results:
        if not ok:
            print(f"  - {name}  {detail}")
    sys.exit(1)
