# Placeholder — will be generated by nixos-anywhere via:
#   just provision hostname=OwO-Family ip=<ip>
# nixos-anywhere --generate-hardware-config nixos-generate-config will
# overwrite this file with the actual hardware config from the target.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Placeholder — will be replaced by nixos-generate-config on the target
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # fileSystems are managed by disko (disk-layout.nix)
  # hardware-configuration.nix will add initrd kernel modules after
  # nixos-anywhere generates it on the target.

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}