# UwU-Server (Beelink SER10 Max) configuration entry point.
# Feature files are automatically imported top-level modules; this entry point
# only selects the merged roles that form the machine.
#
# Roles: common (mango + DMS greeter/shell, NetworkManager, sops, hermes-agent)
# + fileManager (superfile/nautilus) + disk (btrfs dedup timer). Gaming, AMD
# graphics, and the SSH server are host-specific files under this directory.
{ config, inputs, ... }:
{
  flake.nixosConfigurations.UwU-Server = inputs.nixpkgs.lib.nixosSystem {
    system = "x86_64-linux";

    modules = [
      inputs.disko.nixosModules.disko
      config.nixos.modules.common
      config.nixos.modules.privateAccounts
      config.nixos.modules.fileManager
      config.nixos.modules.disk
      config.nixos.hosts."UwU-Server"

      # Generated by nixos-generate-config; deliberately remains a lower-level
      # module so regeneration tools can replace it safely.
      ./hardware-configuration.nix

      { nixpkgs.overlays = [ inputs.self.overlays.additions ]; }
      { nixpkgs.overlays = [ (import ../../overlays/millennium.nix { millennium-input = inputs.millennium; }) ]; }
    ];
  };
}
