# UwU-Server (Beelink SER10 Max) configuration entry point.
# Feature files are automatically imported top-level modules; this entry point
# only selects the merged roles that form the machine.
#
# Roles: common (mango + DMS greeter/shell, NetworkManager, sops, hermes-agent)
# + fileManager (superfile/nautilus) + disk (btrfs dedup timer). Gaming, AMD
# graphics, and the SSH server are host-specific files under this directory.
#
# The host's disk layout (disko config — root pool + 2x 4TB data pools) lives
# in `./disk-layout.nix`, which is auto-imported by `flake.nix`'s
# `collectModules` walker. That file defines `nixos.hosts."UwU-Server"` as a
# NixOS module attrset; this entry point reads that attrset and passes it
# into the `modules = [ ... ]` list below, where it joins the nixpkgs module
# system alongside `hardware-configuration.nix` and the upstream disko
# module (line 14). The linkage is by name, not by file path — the
# `config.nixos.hosts."UwU-Server"` read on line 20 is what wires
# `disk-layout.nix` into the system build.
{ config, inputs, ... }:
{
  flake.nixosConfigurations.UwU-Server = inputs.nixpkgs.lib.nixosSystem {
    system = "x86_64-linux";

    modules = [
      inputs.disko.nixosModules.disko
      config.nixos.modules.common
      config.nixos.modules.privateAccounts
      config.nixos.modules.netbirdMesh
      config.nixos.modules.fileManager
      config.nixos.modules.disk

      # Host-specific NixOS module — includes the disko config from
      # ./disk-layout.nix (root pool, data-media pool, data-backup pool),
      # all host service files under this directory, and the package set.
      config.nixos.hosts."UwU-Server"

      # Generated by nixos-generate-config; deliberately remains a lower-level
      # module so regeneration tools can replace it safely.
      ./hardware-configuration.nix

      # UEFI boot-order cleanup — declared in this directory.
      # The walker excludes it from the auto-imported feature set
      # (see flake.nix's `dendriticExceptions`); the host entry point
      # imports the lower-level NixOS module directly because the
      # walker imports files as flake-parts modules which only see
      # `{ lib, config, inputs, ... }`, not the NixOS module system's
      # `{ config, pkgs, lib, ... }`. The structural test
      # (`tests/dendritic-import-coverage-regressions.py`) enforces
      # that this direct import matches the manifest entry.
      ./boot-order.nix

      # ./disk-layout.nix is auto-imported by `flake.nix`'s `collectModules`
      # walker. See the comment at the top of this file for the full
      # linkage explanation.

      # witr — process/port/container/file tracing CLI ("why is this
      # running?"). Module provided by flake.nix's flake.nixosModules.witr
      # output; overlay below exposes pkgs.witr so the module can reference
      # it like any other system package.
      inputs.self.nixosModules.witr

      { nixpkgs.overlays = [ inputs.self.overlays.additions ]; }
      { nixpkgs.overlays = [ (import ../../overlays/millennium.nix { millennium-input = inputs.millennium; }) ]; }
      {
        # Netbird mesh — sole mesh on this host as of 2026-08-09.
        # See docs/netbird-mesh.md for the migration rationale. The
        # pre-Netbird mesh (Tailscale) had its remoteMesh opt-in
        # removed in the same commit.
        services.netbirdMesh = {
          enable = true;
          nodeRole = "private";
          exposeSshOnLan = true;
          # The netbird daemon binds its mesh DNS resolver on
          # 127.0.0.1:5353 instead of the default mesh IP:5053.
          # AdGuard on this host forwards `*.netbird.cloud` queries
          # to that loopback address (see hosts/UwU-Server/network/
          # direct-link.nix), so UwU and any other host whose
          # resolv.conf points at this AdGuard gets mesh DNS without
          # any per-host DNS plumbing. Port 5353 avoids the
          # CAP_NET_BIND_SERVICE cap that < 1024 would force on the
          # hardened netbird-mesh service.
          dnsResolverAddress = "127.0.0.1";
          dnsResolverPort = 5353;
          # The DMS greeter from modules/wm/dms/dms.nix (loaded by
          # nixos.modules.common) renders the NetbirdStatus plugin
          # against `which netbird`. Even though UwU-Server is
          # headless, the greeter + a future netbird-ui dashboard
          # both need the bare-name shim.
          dms.enable = true;
        };
      }
    ];
  };
}
