# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# NOTE: hand-written and reviewed for the Beelink SER10 Max
# (Ryzen AI 9 HX 470 / Radeon 890M), based on the live-ISO hardware observed in
# 2026-08-03. The guarded provisioning workflow deliberately does not regenerate
# this file because generated fileSystems conflict with Disko. Re-run
# nixos-generate-config manually in a trusted live environment and review the
# hardware-only changes when the hardware changes.
{ config, lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # AMD IOMMU (AMD-Vi) runs in full-translation mode by default on this
  # Beelink SER10 Max (Ryzen AI 9 HX 470). This breaks iwlwifi RX frame
  # aggregation on the Intel AX200 — DMA mappings for aggregated frames
  # fail, collapsing RX to MCS0 (6.5 Mbit/s) while TX stays at full rate.
  # iommu=pt puts the IOMMU in passthrough mode (only translates for
  # devices that opt in), letting WiFi DMA work directly.
  boot.kernelParams = [ "iommu=pt" ];

  # NOTE: no fileSystems entries — filesystems are managed declaratively by
  # disko (hosts/UwU-Server/disk-layout.nix).

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp194s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
